# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Points',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='body',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='title',
            new_name='name',
        ),
    ]
